name: 'CodeShield AI Security Scanner'
description: 'Enterprise-grade security scanner that detects secrets, vulnerabilities, and injection attacks. 24% cheaper than GitGuardian.'
author: 'Lydia Morgan'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  path:
    description: 'Path to scan (default: current directory)'
    required: false
    default: '.'
  
  output-format:
    description: 'Output format: text, json, or html'
    required: false
    default: 'text'
  
  severity:
    description: 'Minimum severity to report: LOW, MEDIUM, HIGH, CRITICAL'
    required: false
    default: 'MEDIUM'

outputs:
  issues-found:
    description: 'Number of security issues found'
  
  report-path:
    description: 'Path to the generated security report'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install --break-system-packages -r ${{ github.action_path }}/requirements.txt
    
    - name: Run CodeShield Scanner
      shell: bash
      run: |
        python ${{ github.action_path }}/run_scan.py ${{ inputs.path }}
      env:
        OUTPUT_FORMAT: ${{ inputs.output-format }}
        MIN_SEVERITY: ${{ inputs.severity }}