"""
CodeShield AI - Security Scanner with AutoFix AI
Works both standalone and as a GitHub Action.
"""

import sys
import os
import urllib.request
import json
from src.scanner import CodeShieldScanner


def validate_license_lemonsqueezy(license_key):
    """Validate license key with LemonSqueezy API."""
    if not license_key:
        return False, None

    try:
        url = "https://api.lemonsqueezy.com/v1/licenses/validate"
        data = json.dumps({"license_key": license_key}).encode('utf-8')

        req = urllib.request.Request(
            url,
            data=data,
            headers={'Content-Type': 'application/json'},
            method='POST'
        )

        with urllib.request.urlopen(req, timeout=10) as response:
            result = json.loads(response.read().decode('utf-8'))

            if result.get('valid'):
                product_name = result.get('meta', {}).get('product_name', '').lower()
                if 'team' in product_name:
                    return True, 'team'
                else:
                    return True, 'pro'

            return False, None

    except Exception as e:
        print(f"License validation warning: {e}")
        return False, None


def create_github_pr(findings, repo, token):
    """Create a GitHub Pull Request with AutoFix AI suggestions."""
    if not findings or not token:
        return None

    try:
        import base64
        import datetime

        branch_name = f"codeshield-autofix-{datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}"

        headers = {
            'Authorization': f'token {token}',
            'Content-Type': 'application/json',
            'Accept': 'application/vnd.github.v3+json'
        }

        base_url = f"https://api.github.com/repos/{repo}"

        ref_url = f"{base_url}/git/refs/heads/main"
        req = urllib.request.Request(ref_url, headers=headers)
        with urllib.request.urlopen(req) as response:
            ref_data = json.loads(response.read().decode('utf-8'))
            sha = ref_data['object']['sha']

        branch_data = json.dumps({
            "ref": f"refs/heads/{branch_name}",
            "sha": sha
        }).encode('utf-8')

        branch_url = f"{base_url}/git/refs"
        req = urllib.request.Request(branch_url, data=branch_data, headers=headers, method='POST')
        urllib.request.urlopen(req)

        pr_body = "## 🛡️ CodeShield AutoFix AI - Security Issues Detected\n\n"
        pr_body += "CodeShield AI has detected the following security issues and generated fix suggestions:\n\n"

        for i, finding in enumerate(findings[:5], 1):
            pr_body += f"### Issue #{i}: {finding.get('vulnerability', 'Security Issue')}\n"
            pr_body += f"- **File:** `{finding.get('file', 'Unknown')}`\n"
            pr_body += f"- **Line:** {finding.get('line', 0)}\n"
            pr_body += f"- **Severity:** {finding.get('severity', 'HIGH')}\n\n"

            autofix = finding.get('autofix')
            if autofix:
                pr_body += "**AutoFix AI Suggestion:**\n"
                pr_body += f"```\n{autofix.get('fix_code', '')}\n```\n\n"
                pr_body += "**Steps to fix:**\n"
                for step in autofix.get('steps', []):
                    pr_body += f"{step}\n"
                pr_body += "\n---\n\n"

        pr_body += "\n\n*Generated by [CodeShield AI](https://codeshield.ie) - AutoFix AI*"

        pr_data = json.dumps({
            "title": f"🛡️ CodeShield AutoFix: {len(findings)} security issue(s) detected",
            "body": pr_body,
            "head": branch_name,
            "base": "main"
        }).encode('utf-8')

        pr_url = f"{base_url}/pulls"
        req = urllib.request.Request(pr_url, data=pr_data, headers=headers, method='POST')
        with urllib.request.urlopen(req) as response:
            pr_result = json.loads(response.read().decode('utf-8'))
            return pr_result.get('html_url')

    except Exception as e:
        print(f"AutoFix PR creation warning: {e}")
        return None


def main():
    print("=" * 60)
    print("  CODESHIELD AI - SECURITY SCANNER WITH AUTOFIX AI")
    print("=" * 60)
    print()

    license_key = os.environ.get('INPUT_LICENSE-KEY', '')
    is_licensed, plan_type = validate_license_lemonsqueezy(license_key)

    if is_licensed:
        print(f"✅ License validated: {plan_type.upper()} plan")
        print(f"✅ AutoFix AI: ENABLED")
    else:
        print("ℹ️  Running in FREE mode (public repos only)")
        print("ℹ️  AutoFix AI suggestions included in report")

    print()

    scanner = CodeShieldScanner()

    target = sys.argv[1] if len(sys.argv) > 1 else os.environ.get('INPUT_TARGET', 'examples/vulnerable_code.py')

    fail_on_issues = os.environ.get('INPUT_FAIL-ON-ISSUES', 'true').lower() == 'true'
    is_private_repo = os.environ.get('GITHUB_REPOSITORY_PRIVATE', 'false').lower() == 'true'
    github_token = os.environ.get('INPUT_GITHUB-TOKEN', '')
    github_repo = os.environ.get('GITHUB_REPOSITORY', '')
    create_pr = os.environ.get('INPUT_CREATE-PR', 'false').lower() == 'true'

    if is_private_repo and not is_licensed:
        print()
        print("❌ ERROR: Private repository scanning requires a Pro or Team license.")
        print("   Get your license at: https://codeshield.ie#pricing")
        print()
        print("   To use your license key, add it to your GitHub Action:")
        print("   - uses: Lydiamorgan85/codeshield-ai@v1.0.2")
        print("     with:")
        print("       license-key: ${{ secrets.CODESHIELD_LICENSE }}")
        sys.exit(1)

    print(f"🔍 Scanning: {target}")
    print()

    if os.path.isfile(target):
        findings = scanner.scan_file(target)
    elif os.path.isdir(target):
        findings = scanner.scan_directory(target)
    else:
        print(f"❌ Error: {target} is not a valid file or directory")
        sys.exit(1)

    report = scanner.generate_report()
    print(report)

    with open('codeshield-report.txt', 'w') as f:
        f.write(report)
    print("📄 Report saved to: codeshield-report.txt")

    if findings and create_pr and github_token and github_repo and is_licensed:
        print()
        print("🤖 AutoFix AI: Creating Pull Request with fix suggestions...")
        pr_url = create_github_pr(findings, github_repo, github_token)
        if pr_url:
            print(f"✅ AutoFix PR created: {pr_url}")
        else:
            print("⚠️  AutoFix PR creation failed - check token permissions")

    if os.environ.get('GITHUB_ACTIONS'):
        github_output = os.environ.get('GITHUB_OUTPUT')
        if github_output:
            with open(github_output, 'a') as f:
                f.write(f"issues-found={len(findings)}\n")
                critical = len([i for i in findings if i.get('severity') in ['HIGH', 'CRITICAL']])
                f.write(f"critical-issues={critical}\n")
                f.write(f"report-path=codeshield-report.txt\n")

    if fail_on_issues and findings:
        critical_count = len([i for i in findings if i.get('severity') in ['HIGH', 'CRITICAL']])
        if critical_count > 0:
            print()
            print(f"❌ Build failed: Found {critical_count} critical security issues")
            print("   Fix the issues above and push again")
            sys.exit(1)

    print()
    print("✅ CodeShield scan complete!")
    sys.exit(0)


if __name__ == "__main__":
    main()